### ISSUE TITLE
crash on find5/AOKP

### ISSUE THREAD

**Issue by stdev293** [stdev293/battery-waster-android#1]
on a _find5_ device with a custom _AOKP_ ROM (just one occurence reported on v6, Sept. 16th 2013)

> java.lang.ArrayIndexOutOfBoundsException:
> at android.hardware.Sensor.getReportingMode(Sensor.java:224)
> at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:105)
> at android.hardware.SensorManager.registerListener(SensorManager.java:689)
> at android.hardware.SensorManager.registerListener(SensorManager.java:616)
> at com.stdev293.batterywasterdemo.sinks.MotionSensors.startImpl(MotionSensors.java:52)
> at com.stdev293.batterywasterdemo.sinks.Sink.start(Sink.java:28)
> at com.stdev293.batterywasterdemo.activities.BatteryWasterActivity.startWasting(BatteryWasterActivity.java:176)
> at > com.stdev293.batterywasterdemo.sinks.SinksControlThread$SinksControlActionHandler.handleMessage(SinksControlThread.java:67)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:137)
> at com.stdev293.batterywasterdemo.sinks.SinksControlThread.run(SinksControlThread.java:119)

**Comment by stdev293** [comment]
the error is caused by an uncontrolled index in an array in Sensor.java (AOKP source: https://github.com/AOKP/frameworks_base/blob/jb-mr2/core/java/android/hardware/Sensor.java) -- this is _out_ of the app source code.
Since there is no other instance of this crash, and it seems to be happening 100% of the time for the user who reported it, my guess is that this error is either due to an error in AOKP source code or configuration, or some incompatibility between AOKP and the find5 device (the app attempts to turn on each listed sensor).

**Comment by stdev293** [comment]
==> labeled wontfix
